language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t michalboljesik/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true michalboljesik/docker-react npm run test